### ISSUE TITLE
Install playbook requirements

### ISSUE THREAD

**Issue by fooock** [dawidd6/action-ansible-playbook#12]
I want to use your action but I need to install my playbook requirements first in order to make it work. I think that currently is not possible (I don't see any reference to it in the `action.yml`).

An approach can be:

```yaml
- name: Execute playbook
   uses: dawidd6/action-ansible-playbook@v2
   with:
     playbook: playbook.yml
     requirements: requirements.yml
```
If the `requirements` field is present, then first it tries to download all required roles/collections and then execute the playbook. What do you think?

Nice work!
