### ISSUE TITLE
Add capacity to select the working directory of the ansible content

### ISSUE THREAD

**Issue by blyndusk** [dawidd6/action-ansible-playbook#2]
First of all, great idea !

I wanted to use your action, but my project is like this :

```bash
root
└── config
    └── ansible
```

and GitHub action **do not allow** `uses` and `working-directory` on the **same step**:

```YAML
- name: deploy
  uses: dawidd6/action-ansible-playbook
  # not posible !
  working-directory: ./config/ansible
  with:
    playbook: app.yml
    key: ${{ secrets.SSH_PRIVATE_KEY }}
    options: |
      --inventory inventory.ini
      --user ubuntu
      --tags "deploy"
      --verbose
```

Is possible to add the working directory **as a `with:` parameter** ?
