### ISSUE TITLE
SSH Issues – a bit more documentation would be nice

### ISSUE THREAD

**Issue by vardumper** [dawidd6/action-ansible-playbook#36]
In order to make sure ansible has access to the boxes, I needed to remove the following line form my inventory file. Also I had to comment out the known_hosts setting.

I had the line in all:vars section
```
[all:vars]
ansible_ssh_private_key_file = ~/.ssh/id_rsa
```

After removing it, the playbook action could connect.

**Comment by clincha** [comment]
@vardumper agree it would be nice to have some documentation advising against setting the ansible_ssh_private_key_file value in the README. I'm not the best at node.js but it looks like the key is copied to a file called ".ansible_key" so you might be able to set ansible_ssh_private_key_file to that but easier to just omit it.

```javascript
if (key) {
    const keyFile = ".ansible_key"
    fs.writeFileSync(keyFile, key + os.EOL, { mode: 0600 })
    core.saveState("keyFile", keyFile)
    cmd.push("--key-file")
    cmd.push(keyFile)
}
```

**Comment by MasteringBOX** [comment]
I can't connect :/  I tried both suggestions and I got a permission denied error. I stored the private key string in an action secret and added it to the "key" variable. Is there anything I'm missing?

**Comment by jozef-valko** [comment]
> EDIT: I solved it

@MasteringBOX could you please elaborate more how you have fixed this? I'm facing the similar issue, looks like action is ignoring the value of `key` parameter.

**Comment by jozef-valko** [comment]
@MasteringBOX I made it work, it was issue on my side with SSH keys and config. After generating new SSH keypair and setting parameters correctly:
```
- name: deploy stuff
   uses: dawidd6/action-ansible-playbook@v2
   with:
   playbook: deploy.yaml
   key: ${{ secrets.SSH_KEY }}
   options: |
     --user ssh_user
     --ssh-extra-args "-o StrictHostKeyChecking=no"
```
and setting `--ssh-extra-args "-o StrictHostKeyChecking=no"` GH action was able to connect to machines successfully.
