### ISSUE TITLE
Feature Request: GitHub Actions / Ansible Callback Plugin

### ISSUE THREAD

**Issue by corym-vermeer** [dawidd6/action-ansible-playbook#55]
Has anyone seen a custom callback plugin for Ansible which utilizes the various workflow-commands in GitHub to improve the overall readability?   

https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions

Best I've gotten so far is using debug.   
Here is an example of using env vars to set the callback. 

```yaml
        uses: 'dawidd6/action-ansible-playbook@v2.5.0'
        env:
          ANSIBLE_STDOUT_CALLBACK: debug
          ANSIBLE_DISPLAY_FAILED_STDERR: yes
          ANSIBLE_CALLBACK_FORMAT_PRETTY: yes
```

**Comment by corym-vermeer** [comment]
Here is my current working solution.  I'm sure there are better ways to do this though I'm not finding much for published examples.

## GitHub Action Step
```yaml
    - name: Run Playbook
      uses: 'dawidd6/action-ansible-playbook@v2'
      env:
        ANSIBLE_STDOUT_CALLBACK: debug
        ANSIBLE_DISPLAY_FAILED_STDERR: yes
        ANSIBLE_SHOW_TASK_PATH_ON_FAILURE: yes
      with:
        playbook: 'playbook.yml'
        directory: ./
        requirements: requirements.yml
        options: |
          --inventory hosts.yml
          --extra-vars github_summary_file=${{ inputs.github_summary_file }}
          --check
    - name: Create Github Step Summary
      if: always()
      shell: bash
      run: |
        if [[ -r "${{ inputs.github_summary_file }}" ]]; then
          cat ${{ inputs.github_summary_file }} >> $GITHUB_STEP_SUMMARY
        else 
          echo "Missing Step Summary File (${{ inputs.github_summary_file }} )"
        fi
```
## Ansible Playbook snippet to create the summary file using a template
```yaml
- name: "Create gitHub summary {{ github_summary_file }}"
  ansible.builtin.template:
    src: github_summary.md.j2
    dest: "{{ github_summary_file }}"
  with_items:
    - "{{ output }}"
  delegate_to: localhost
  become: false
  when:
    github_summary_file is defined
```
