### ISSUE TITLE
Ansible Galaxy : command not found

### ISSUE THREAD

**Issue by nlamirault** [dawidd6/action-ansible-playbook#66]
Hi, 
I try your Github Action to execute an Ansible playbook :

```yaml
name: Test / Linux

on:
  # - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Run Ansible playbook
        uses: dawidd6/action-ansible-playbook@v2.6.1
        with:
          playbook: divona_linux.yml
          directory: ./
          requirements: divona/requirements-linux.yml
          # the ssh private key for ansible to use to connect to the servers, stored as "ansible_ssh_private_key" in the GitHub secrets
          # key: ${{ secrets.ansible_ssh_private_key }}
          # the ansible inventory to use, stored as "ansible_inventory" in the GitHub secrets
          inventory: inventories/linux.ini
          options: |
            --verbose
```

and the output :

```
Run dawidd6/action-ansible-playbook@v2.6.1
  with:
    playbook: divona_linux.yml
    directory: ./
    requirements: divona/requirements-linux.yml
    inventory: inventories/linux.ini
    options: --verbose
  
Error: Unable to locate executable file: ansible-galaxy. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
```

Do you have any idea ?
