### ISSUE TITLE
ansible-playbook not found on private runner

### ISSUE THREAD

**Issue by slaurijssen** [dawidd6/action-ansible-playbook#74]
Trying to run a playbook on a private runner to update an internal cluster

```
  build:
    name: Run free_disk_space
    runs-on: self-hosted
    steps:
     - name: checkout repo content
       uses: actions/checkout@v3 # checkout the repository content    
     - name: Run playbook
       uses: dawidd6/action-ansible-playbook@v2
       with:
        playbook: all_vms/free_disk_space.yml
        key: ${{secrets.ANSIBLE_KEY}}
     - name: ls
       if: always()
       run: ls -la /opt/pipx_bin
```

But self-hosted runner gets the error that ansible-playbook cant be found or is not executable.

``` runs-on: ubuntu-latest ``` works but then the servers cant be accessed. There it is found in /opt/pipx_bin but that does not exist on self-hosted.

So where is the ansible-playbook normally or how to get it running on a private runner?

*edit* I just realized this action does not actually install ansible itself  like the kubectl gh action does. so the solution is to first install ansible.
