### ISSUE TITLE
Support Vault-ID

### ISSUE THREAD

**Issue by audioboxer217** [dawidd6/action-ansible-playbook#8]
I have a client that uses Vault-IDs not just Vault Passwords.

Example:
`ansible-playbook tests/test.yml --vault-id dev@~/vault-passwords/dev`

Options could be to either 
- just have it be a full entry like what would be entered in the CLI (i.e vault_id: 'dev@~/vault-passwords/dev')
- add 'vault_password_file' and  'vault_id' parameters and put them together when both are passed.

I know there are several other considerations that come up with this.  Such as, what about when someone passed 'vault_password' and 'vault_password_file' or if someone passes 'vault_id' but no 'vault_password_file'.  However, I think these could be handled fairly easily.

If I have some time, I may try to tackle this myself and open a PR.

**Comment by audioboxer217** [comment]
Yep, that worked.  Not entirely intuitive, but probably much simpler to implement.  😁 

```yaml
- name: Run Test Playbook
  uses: dawidd6/action-ansible-playbook@v2
  with:
    playbook: test.yml
    directory: deploy_configs/tests
    options: | 
      --vault-id dev@/home/runner/vault-passwords/dev
```
