### ISSUE TITLE
make action fail if no hosts were updated

### ISSUE THREAD

**Issue by 20k-ultra** [dawidd6/action-ansible-playbook#86]
I'm trying to get the use of this action to fail instead of pass when no hosts were updated. This can happen for various reasons but I don't want my CI to think the changes were actually deployed when no hosts were found from the inventory file.

This could also just be a configuration file to avoid introducing a breaking change.

Alternatively, I've tried to store the output of this action and grep it for `no hosts matched` but the issue is I need this action to write to GITHUB a output var. I can't just read the stdout of a step.

**Comment by 20k-ultra** [comment]
I've worked around the warning not causing a fail in this action by adding the following step to my playbook which makes a step fail.

```
- name: Check if host group is empty
  hosts: localhost
  any_errors_fatal: true
  gather_facts: no
  tasks:
    - name: Fail if hosts group is empty
      fail:
        msg: "Inventory for 'proxy' is empty. Exiting playbook."
      when: "'proxy' not in groups or (groups['proxy'] | length == 0)"
```
